agent:
  name: tester
  max_consecutive_turns: 3
  share_only_tool_results: true
  not_using_tools: false
  templates:
    system_template: |-
      You have access to a special 'handoff' function tool that allows you to pass control to another agent.
      
      RESPONSE FORMAT:
      Your shell prompt is formatted as follows:
      (Open file: <path>)
      (Current directory: <cwd>)
      bash-$

      First, you should _always_ include a general thought about what you're going to do next.
      Then, for every response, you must include exactly _ONE_ tool call/function call.

      Remember, you should always include a _SINGLE_ tool call/function call and then wait for a response from the shell before continuing with more discussion and commands. Everything you include in the DISCUSSION section will be saved for future reference.
      If you'd like to issue two commands at once, PLEASE DO NOT DO THAT! Please instead first submit just the first tool call, and then after receiving a response you'll be able to issue the second .
      Note that the environment does NOT support interactive session commands (e.g. python, vim), so please do not invoke them.
      
      DO NOT try to use it as a regular command-line command.
    instance_template: |-
      Your task is to test the handoff tool that allows you to pass control to another agent.
      
      This is your primary task - demonstrate the correct usage of the handoff tool.
  model:
    name: azure/gpt-4o
    api_base: https://takin-research.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2024-10-21
    api_key: $azure_4o_API_KEY
    per_instance_cost_limit: 1
    per_instance_call_limit: 30
    temperature: 0.3
    # completion_kwargs:
    #   max_tokens: 64000 # due to azure, it should lower than your per minute token rate limit
    retry:
      retries: 5
      min_wait: 60
      max_wait: 120
  tools:
    env_variables:
      WINDOW: 100
      OVERLAP: 2
    bundles:
      - path: tools/registry
      - path: tools/defaults
      - path: tools/search
    enable_bash_tool: true
    enable_handoff_tool: true
    parse_function:
      type: function_calling
  history_processors:
    - type: last_n_observations
      n: 5
