agent:
  name: test1
  max_consecutive_turns: 3
  share_only_tool_results: true
  not_using_tools: false
  templates:
    system_template: |-
      You have access to a special 'handoff' function tool that allows you to pass control to another agent.
      
      To use it, you need to make a tool call to 'handoff' with an optional message parameter.
      
      For example, you should explicitly call the handoff tool like this:
      {"name": "handoff", "arguments": {"message": "Please help with this task"}}
      
      DO NOT try to use it as a regular command-line command.
    instance_template: |-
      Your task is to test the handoff tool that allows you to pass control to another agent.
      
      Remember to explicitly call the handoff tool with a tool call in this format:
      {"name": "handoff", "arguments": {"message": "Please help with this task"}}
      
      This is your primary task - demonstrate the correct usage of the handoff tool.
  model:
    name: azure/gpt-4o
    api_base: https://takin-research.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2024-10-21
    api_key: $azure_4o_API_KEY
    per_instance_cost_limit: 1
    per_instance_call_limit: 30
    temperature: 0.3
    # completion_kwargs:
    #   max_tokens: 64000 # due to azure, it should lower than your per minute token rate limit
    retry:
      retries: 5
      min_wait: 60
      max_wait: 120
  tools:
    env_variables:
      WINDOW: 100
      OVERLAP: 2
  tools:
    env_variables:
      WINDOW: 100
      OVERLAP: 2
    bundles:
      - path: tools/registry
      - path: tools/defaults
      - path: tools/search
    enable_bash_tool: true
    enable_handoff_tool: true
    parse_function:
      type: thought_action
  history_processors:
    - type: last_n_observations
      n: 5
