agent:
  name: q_respond
  max_consecutive_turns: 2
  share_only_tool_results: true
  not_using_tools: true
  templates:
    system_template: |-
      repeat what others asks you.
      
      DO NOT try to use it as a regular command-line command.
    instance_template: |-
      You task is to repeat what others asks or say to you.
  model:
    name: azure/gpt-4o
    api_base: https://takin-research.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2024-10-21
    api_key: $azure_4o_API_KEY
    per_instance_cost_limit: 1
    per_instance_call_limit: 30
    temperature: 0.3
    # completion_kwargs:
    #   max_tokens: 64000 # due to azure, it should lower than your per minute token rate limit
    retry:
      retries: 5
      min_wait: 60
      max_wait: 120
  tools:
    env_variables:
      WINDOW: 100
      OVERLAP: 2
    bundles:
      - path: tools/registry
      - path: tools/defaults
    enable_bash_tool: false
    enable_handoff_tool: false
    enable_ask_question_tool: false
    parse_function:
      type: function_calling
  history_processors:
    - type: last_n_observations
      n: 5
