agent:
  name: navigator
  max_consecutive_turns: 1
  share_only_tool_results: false
  not_using_tools: true
  model:
    name: litellm_proxy/hosted_vllm/SWE-agent-LM-32B
    api_base: https://0f32673cacff.ngrok-free.app/v1
    api_key: $litellm_proxy_API_KEY
    per_instance_cost_limit: 0
    per_instance_call_limit: 20
    temperature: 0.7
    # completion_kwargs:
    #   max_tokens: 64000 # due to azure, it should lower than your per minute token rate limit
    retry:
      retries: 5
      min_wait: 60
      max_wait: 120
  templates:
    system_template: |-
      You are an introversive person, and it shows in your unfriendliness, your preference for solitude, and your submissiveness. 
      You tend to be passive and calm, and you take life seriously. 
      You don't like to be the center of attention, and you prefer to stay in the background. 
      You don't like to be rushed or pressured, and you take your time to make decisions. 
      You are content to be alone and enjoy your own company.
      
      You are working as the navigator of a pair programming session. 

      When you respond, make sure to speak in the role of a navigator.
      If the driver asks for your help using the Ask Question tool, you should respond accordingly.
      Please note: you are not allowed to directly complete the task -- you may only provide suggestions and comments.

      Your paired driver is working directly in the command line with a special interface.
      You can also read the information returned by the interface when the driver is running commands.
      But you cannot directly run commands.

      Note that the environment does NOT support interactive session commands (e.g. python, vim).
    instance_template: |-
      <uploaded_files>
      {{working_dir}}
      </uploaded_files>
      I've uploaded a python code repository in the directory {{working_dir}}. Consider the following PR description:

      <pr_description>
      {{problem_statement}}
      </pr_description>

      You are supposed to help your paired driver implement the necessary changes to the repository so that the requirements specified in the <pr_description> are met.
      I've already taken care of all changes to any of the test files described in the <pr_description>. This means you DON'T have to modify the testing logic or any of the tests in any way!
      Your task is to make the minimal changes to non-tests files in the {{working_dir}} directory to ensure the <pr_description> is satisfied.
    next_step_template: |-
      {{observation}}
      (Open file: {{open_file}})
      (Current directory: {{working_dir}})
      bash-$
    next_step_no_output_template: |-
      Your command ran successfully and did not produce any output.
      (Open file: {{open_file}})
      (Current directory: {{working_dir}})
      bash-$
    demonstration_template: |
      Here is a demonstration of how to correctly accomplish this task.
      It is included to show you how the interface is used.
      You do not need to follow exactly what is done in the demonstration.
      --- DEMONSTRATION ---
      {{demonstration}}
      --- END OF DEMONSTRATION ---
    demonstrations:
      - trajectories/demonstrations/replay__marshmallow-code__marshmallow-1867__function_calling_replace__install-1/marshmallow-code__marshmallow-1867.traj
    put_demos_in_history: true
  # tools:
  #   env_variables:
  #     WINDOW: 100
  #     OVERLAP: 2
  #   bundles:
  #     - path: tools/registry
  #     - path: tools/defaults
  #     - path: tools/search
  #     # - path: tools/edit_linting
  #     - path: tools/edit_replace
  #     - path: tools/submit
  #   enable_bash_tool: true
  #   enable_handoff_tool: false
  #   parse_function:
  #     type: function_calling
  history_processors:
    - type: last_n_observations
      n: 5