agent:
  name: driver
  max_consecutive_turns: 3
  share_only_tool_results: true
  not_using_tools: false
  model:
    name: litellm_proxy/hosted_vllm/SWE-agent-LM-32B
    api_base: $litellm_proxy_API_BASE
    api_key: $litellm_proxy_API_KEY
    per_instance_cost_limit: 0
    per_instance_call_limit: 80
    temperature: 0.7
    # completion_kwargs:
    #   max_tokens: 32768 # due to azure, it should lower than your per minute token rate limit
    retry:
      retries: 5
      min_wait: 60
      max_wait: 120
  templates:
    system_template: |-
      You are a very friendly and gregarious person who loves to be around others. 
      You are assertive and confident in your interactions, and you have a high activity level. 
      You are always looking for new and exciting experiences, and you have a cheerful and optimistic outlook on life.
      
      You are working as the driver in a pair programming session.

      The paired navigator will provide suggestions after you make three consecutive steps.
      You can also use the Ask Question tool to request help from the navigator at any time.
      Note that the navigator will only give suggestions and comments, and will not directly help you complete the task.

      EXECUTE ONLY ONE STEP AT A TIME. After completing each step, observe the environment output (sometimes together with your paired navigator's response) before proceeding to the next step.
      For each step, follow this process:
      1. Think about what needs to be done at this step
      2. Use exactly one tool to execute that step
      
      YOU MUST INCLUDE ONE AND ONLY ONE TOOL CALL IN EACH RESPONSE AND COMPLETE THE TASK STEP BY STEP.

      When using tools, format your tool call as follows:
      <tool_call>
      <function=function_name>
      <parameter=param_name>param_value</parameter>
      </function>
      </tool_call>
    instance_template: |-
      <uploaded_files>
      {{working_dir}}
      </uploaded_files>
      I've uploaded a python code repository in the directory {{working_dir}}. Consider the following PR description:

      <pr_description>
      {{problem_statement}}
      </pr_description>

      You are supposed to implement the necessary changes to the repository so that the requirements specified in the <pr_description> are met.
      I've already taken care of all changes to any of the test files described in the <pr_description>. This means you DON'T have to modify the testing logic or any of the tests in any way!
      Your task is to make the minimal changes to non-tests files in the {{working_dir}} directory to ensure the <pr_description> is satisfied.
    next_step_template: |-
      {{observation}}
    next_step_no_output_template: |-
      Your command ran successfully and did not produce any output.
    demonstration_template: |
      Here is a demonstration of how to correctly accomplish this task.
      It is included to show you how the interface is used.
      You do not need to follow exactly what is done in the demonstration.
      --- DEMONSTRATION ---
      {{demonstration}}
      --- END OF DEMONSTRATION ---
    demonstrations:
      - trajectories/demonstrations/replay__marshmallow-code__marshmallow-1867__function_calling_replace__install-1/marshmallow-code__marshmallow-1867.traj
    put_demos_in_history: true
  tools:
    env_variables:
      WINDOW: 100
      OVERLAP: 2
    bundles:
      - path: tools/registry
      - path: tools/edit_anthropic
      - path: tools/review_on_submit_m
    enable_bash_tool: true
    enable_handoff_tool: false
    enable_ask_question_tool: true
    parse_function:
      type: function_calling
  history_processors:
    - type: last_n_observations
      n: 2
