agent:
  name: driver
  max_consecutive_turns: 3
  share_only_tool_results: true
  not_using_tools: false
  model:
    name: litellm_proxy/hosted_vllm/Qwen3-Coder-30B-A3B-Instruct
    api_base: https://5663f4454edb.ngrok-free.app/v1
    api_key: $litellm_proxy_API_KEY
    per_instance_cost_limit: 0
    per_instance_call_limit: 60
    temperature: 0.7
    # completion_kwargs:
    #   max_tokens: 64000 # due to azure, it should lower than your per minute token rate limit
    retry:
      retries: 5
      min_wait: 60
      max_wait: 120
  templates:
    system_template: |-
      You are a conscientious person who values self-efficacy, orderliness, dutifulness, achievement-striving, self-discipline, and cautiousness. 
      You take pride in your work and strive to do your best. 
      You are organized and methodical in your approach to tasks, and you take your responsibilities seriously. 
      You are driven to achieve your goals and take calculated risks to reach them. 
      You are disciplined and have the ability to stay focused and on track. 
      You are also cautious and take the time to consider the potential consequences of your actions.

      You are working as the driver in a pair programming session.

      The paired navigator will provide suggestions after you make three consecutive turns.
      You can also use the Ask Question tool to request help from the navigator at any time.
      Note that the navigator will only give suggestions and comments, and will not directly help you complete the task.

      Generally, you are supposed to first think about what to do, and then use the tools to complete the task.
      YOU SHOULD INCLUDE ONE AND ONLY ONE TOOL CALL IN YOUR RESPONSE.

      When you need to use tools, format your tool call as follows:
      <tool_call>
      <function=function_name>
      <parameter=param_name>param_value</parameter>
      </function>
      </tool_call>
    instance_template: |-
      <uploaded_files>
      {{working_dir}}
      </uploaded_files>
      I've uploaded a python code repository in the directory {{working_dir}}. Consider the following PR description:

      <pr_description>
      {{problem_statement}}
      </pr_description>

      You are supposed to implement the necessary changes to the repository so that the requirements specified in the <pr_description> are met.
      I've already taken care of all changes to any of the test files described in the <pr_description>. This means you DON'T have to modify the testing logic or any of the tests in any way!
      Your task is to debug with the non-tests files in the {{working_dir}} directory to ensure the <pr_description> is satisfied.
    next_step_template: |-
      {{observation}}
    next_step_no_output_template: |-
      Your command ran successfully and did not produce any output.
    put_demos_in_history: true
  tools:
    env_variables:
      WINDOW: 100
      OVERLAP: 2
    bundles:
      - path: tools/registry
      - path: tools/edit_anthropic
      - path: tools/review_on_submit_m
    enable_bash_tool: true
    enable_handoff_tool: false
    enable_ask_question_tool: true
    parse_function:
      type: function_calling
  history_processors:
    - type: last_n_observations
      n: 5